name: pasadena

# backend/docker-compose.yml
services:
  postgres_auth_db:
    image: postgres:15-alpine
    container_name: auth_postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pasadena_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h ${POSTGRES_USER} -U ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5



# auth service
  auth_service:
    build: ./auth-service
    container_name: pasadena_auth_service
    env_file:
      - .env
    environment: 
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - MAIL_ADDRESS=${MAIL_ADDRESS}
      - MAIL_PASS=${MAIL_PASS}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
    ports:
      - "8001:8001"
    command: >
      sh -c "
        until pg_isready -h postgres_auth_db -U ${POSTGRES_USER} -d ${POSTGRES_DB}; do
          echo 'Esperando a PostgreSQL...';
          sleep 2;
        done;
        echo 'Base de datos lista. Ejecutando migraciones...';
        alembic upgrade head;
        echo 'Migraciones completadas. Iniciando servidor...';
        uvicorn app.main:app --host 0.0.0.0 --port 8001"
    depends_on:
      - postgres_auth_db
      - redis
      - user_service
    networks:
      - pasadena_network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8001/health')"]
      interval: 5s
      timeout: 3s
      retries: 5

# Redis to send codes
  redis:
    image: redis:7-alpine
    container_name: pasadena_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pasadena_network

# user MongoDB
  mongo_user_db:
    image: mongo:6-jammy
    container_name: user_mongo
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_USER_DB}
    ports:
      - "27018:27017"
    volumes:
      - mongo_user_data:/data/db
    networks: 
      - pasadena_network
    healthcheck:
      test: mongosh --username ${MONGO_INITDB_ROOT_USERNAME} --password ${MONGO_INITDB_ROOT_PASSWORD} --eval "db.adminCommand('ping')"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

# user service
  user_service:
    build: ./user-service
    container_name: pasadena_user_service
    env_file:
      - .env
    environment:
      - DATABASE_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo_user_db:27017/${MONGO_USER_DB}?authSource=admin
    ports:
      - "8003:8003"
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8003"
    depends_on:
      mongo_user_db:
        condition: service_healthy
    networks:
      - pasadena_network

# Playlist Postgres DB
  postgres_playlist_db:
    image: postgres:15-alpine
    container_name: playlist_postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_PLAYLIST_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_playlist_data:/var/lib/postgresql/data
    networks:
      - pasadena_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h ${POSTGRES_PLAYLIST_HOST} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

# playlists service
  playlist_service:
    build: ./playlist-service
    container_name: pasadena_playlist_service
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_playlist_db:5432/${POSTGRES_PLAYLIST_DB}
    ports:
      - "8002:8002"
    command: >
      sh -c "
        until pg_isready -h postgres_playlist_db -U papu; do
          echo 'Esperando a PostgreSQL...';
          sleep 2;
        done;
        echo 'Base de datos lista. Ejecutando migraciones...';
        alembic upgrade head;
        echo 'Migraciones completadas. Iniciando servidor...';
        uvicorn app.main:app --host 0.0.0.0 --port 8002"
    depends_on:
      - postgres_playlist_db
    networks:
      - pasadena_network
    volumes:
      - ./playlist-service/app/static:/app/static

# admin postgres db
  admin_service:
    build: ./admin-service
    container_name: pasadena_admin_service
    env_file:
      - .env
    environment:
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
    ports:
      - "8004:8004"
    depends_on:
      - auth_service
    networks:
      - pasadena_network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8004/health')"]
      interval: 5s
      timeout: 3s
      retries: 5


# API Gateway
  api_gateway:
    build: ./gateway
    container_name: pasadena_gateway
    ports: 
      - "8080:80"
    depends_on:
      - auth_service
      - playlist_service
      - user_service
      - admin_service
    networks:
      - pasadena_network

volumes:
  postgres_data:
  postgres_playlist_data:
  mongo_data:
  redis_data: 
  mongo_user_data:

networks:
  pasadena_network:
    driver: bridge